### ISSUE TITLE
Enable jupyter magic commands to load and verify problems

### ISSUE THREAD

**Issue by anandology** [pipalacademy/arcesium-python-2024#5]
## Tasks

- [x] Add the code the repo
- [x] setup jupyter to autoload the magic commands
- [x] setup problems in the repository
- [x] setup a place to add files used by these problems

**Comment by anandology** [comment]
Done.
