### ISSUE TITLE
Assignment Grading workflow

### ISSUE THREAD

**Issue by anandology** [pipalacademy/arcesium-python-2024#6]
## Tasks

- [ ] Document how to create assignments
- [ ] Document how to grade the assignments and review the notebooks of the students
- [ ] Document how to create new problems
